### ISSUE TITLE
Feat: Add testing action

### ISSUE THREAD

**Issue by rulasg** [rulasg/TestingHelper#40]
As a developer
I want a testing action on GitHub repo to enable a gate to control code defects from release
so that we can go faster and release with automation control

**Comment by rulasg** [comment]
Use DemoPsModule as reference.

https://github.com/rulasg/DemoPsModule/blob/main/.github/workflows/test_with_TestingHelper.yml

``` yaml
# This is a basic workflow to help you get started with Actions

name: Test with TestingHelper

# Controls when the workflow will run
on:

  # Run as check on pull request
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run test.ps1
        run: | 
          $result = ./test.ps1 -ShowTestErrors
          $result
          if($result.Tests -eq $result.Pass){
            "All test passed" | Write-Verbose -verbose
          } else {
            "Some test failed" | Write-Verbose -verbose
            exit 1
          }
        shell: pwsh
```
